[project]
name = "gitignore"
version = "1.2.0"
description = ".gitignore file management util"
readme = "README.md"
authors = [
    { name = "wandderq", email = "wanddr.qq@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
gitignore = "gitignore.gitignore:run_cli"
